In [1]:
# -*- coding: utf-8 -*-
# @Time    : 2021/4/10 18:08
# @Author  : Weiming Mai
# @FileName: main.py
# @Software: PyCharm

import numpy as np
from Nodes import *
from Utils import *
from numpy import *
import xlrd
from sklearn import preprocessing

In [2]:
# read data
def excel_to_matrix(path, num):
    table = xlrd.open_workbook(path).sheets()[num]  # 获取第一个sheet表
    row = table.nrows  # 行数
    col = table.ncols  # 列数
    datamatrix = np.zeros((row, col))  # 生成一个nrows行ncols列，且元素均为0的初始矩阵
    for x in range(col):
        cols = np.matrix(table.col_values(x))  # 把list转换为矩阵进行矩阵操作
        datamatrix[:, x] = cols  # 按列把数据存进矩阵中
        # 数据归一化
        min_max_scaler = preprocessing.MinMaxScaler()
        datamatrix = min_max_scaler.fit_transform(datamatrix)
    return datamatrix

def mini_batch(batch_size, data_X, data_Y):
    idx = np.arange(0, data_X.shape[0])
    np.random.shuffle(idx)
    idx = idx[0:batch_size]

    return data_X[idx,:], data_Y[idx,:]

datafile = "C:/Users/13271/Desktop/git/DL/iris_test+train.xlsx"

data_x = excel_to_matrix(datafile, 0)
data_y = excel_to_matrix(datafile, 3)

x_test = excel_to_matrix(datafile, 1)
y_test = excel_to_matrix(datafile, 2)

In [26]:
batch_size = 32
x_batch, y_batch = mini_batch(batch_size, data_x, data_y)

x = Input(x_batch)
l2 = Dense(x, 10)
l2 = Sigmoid(l2)
l3 = Dense(l2, 8)
l3 = Sigmoid(l3)
l4 = Dense(l3, 8)
l4 = Sigmoid(l4)
l5 = Dense(l4, 6)
l5 = Sigmoid(l5)
l6 = Dense(l5,4)
l6 = Sigmoid(l6)
l7 = Dense(l6,3)
l7 = Sigmoid(l7)


y = Const(y_batch)
cost = MSE(l7, y)

Forward(cost)
p = Train(cost, [])
GD = G_D_Optimizer(p, 0.01) # lr
print(cost.value)
epoch = 1000
for ep in range(epoch):
    x_batch, y_batch = mini_batch(batch_size, data_x,data_y)
    x.value = x_batch
    y.value = y_batch
    for j in range(20):
        Forward(cost)
        Backprop(cost)
        GD.train()
    if ep % 100 == 0:
        print(cost.value)
#
#test = preprocessing.MinMaxScaler().fit_transform(np.array([[5.1,3.4,1.5,0.2]]))
# x.value = np.array([[5.1,3.4,1.5,0.2]])
# x.value = test
Test(cost)
x.value = x_test
Forward(cost)
# Backprop(cost)
print(cost.value)
print(l7.value)

0.7462957152555574
0.6139294770598722
0.6640718098429459
0.6594763320545556
0.6623908437515775
0.6373667469693921
0.6567237073945136
0.6590986012850829
0.6516445699058873
0.6625879877993173
0.6642050244593175
0.584596644129239
[[0.37547583 0.31311283 0.31068724]
 [0.37547583 0.31311283 0.31068724]
 [0.37547598 0.31311302 0.31068741]
 [0.37547589 0.31311291 0.31068731]
 [0.37547581 0.31311281 0.31068722]
 [0.37547577 0.31311276 0.31068718]
 [0.37547589 0.3131129  0.3106873 ]
 [0.37547579 0.31311278 0.31068719]
 [0.37547588 0.31311289 0.3106873 ]
 [0.37547579 0.31311278 0.3106872 ]
 [0.37547585 0.31311286 0.31068726]
 [0.3754758  0.31311282 0.31068721]
 [0.37547578 0.3131128  0.31068719]
 [0.3754757  0.3131127  0.3106871 ]
 [0.37547578 0.31311279 0.31068719]
 [0.37547588 0.31311291 0.31068729]
 [0.37547577 0.31311278 0.31068718]
 [0.37547574 0.31311274 0.31068714]
 [0.37547574 0.31311275 0.31068715]
 [0.37547572 0.31311272 0.31068712]
 [0.37547586 0.31311288 0.31068727]
 [0.37547576 0.31

In [3]:
# hyper parameter：lr, batch size, iteration
batch_size = 32
x_batch, y_batch = mini_batch(batch_size, data_x, data_y)

x = Input(x_batch)
l2 = Dense(x, 10)
l2 = batch_normalize(l2)
l2 = Sigmoid(l2)
l3 = Dense(l2, 8)
l3 = batch_normalize(l3)
l3 = Sigmoid(l3)
l4 = Dense(l3, 8)
l4 = batch_normalize(l4)
l4 = Sigmoid(l4)
l5 = Dense(l4, 6)
l5 = batch_normalize(l5)
l5 = Sigmoid(l5)
l6 = Dense(l5,4)
l6 = batch_normalize(l6)
l6 = Sigmoid(l6)
l7 = Dense(l6,3)
l7 = batch_normalize(l7)
l7 = Sigmoid(l7)


y = Const(y_batch)
cost = MSE(l7, y)

Forward(cost)
p = Train(cost, [])
GD = G_D_Optimizer(p, 0.2) # lr
print(cost.value)
epoch = 1000
for ep in range(epoch):
    x_batch, y_batch = mini_batch(batch_size, data_x,data_y)
    x.value = x_batch
    y.value = y_batch
    for itera in range(5):
        Forward(cost)
        Backprop(cost)
        GD.train()
    if ep % 100 == 0:
        print(cost.value)
#
#test = preprocessing.MinMaxScaler().fit_transform(np.array([[5.1,3.4,1.5,0.2]]))
# x.value = np.array([[5.1,3.4,1.5,0.2]])
# x.value = test
# Test(cost)
x.value = x_test
Forward(l7)
# Backprop(cost)
print(cost.value)
print(l7.value)

0.7561434013600997
0.599619535759922
0.23726836742813348
0.19423007227639721
0.06071571262323765
0.05318298420201939
0.0629437052347744
0.059709192246848626
0.06023108550370163
0.08147861175604242
0.0034073679238116315
0.15565651951320741
[[9.98003190e-01 1.73489782e-05 3.22749436e-10]
 [9.98003127e-01 1.73493387e-05 3.22754589e-10]
 [9.98017789e-01 1.72652942e-05 3.21470996e-10]
 [9.98006532e-01 1.73298349e-05 3.22455249e-10]
 [9.98003156e-01 1.73491768e-05 3.22752521e-10]
 [9.98004586e-01 1.73409810e-05 3.22625730e-10]
 [9.98003142e-01 1.73492551e-05 3.22753316e-10]
 [9.98007616e-01 1.73236253e-05 3.22360380e-10]
 [9.98003523e-01 1.73470742e-05 3.22719373e-10]
 [9.98004185e-01 1.73432822e-05 3.22661095e-10]
 [9.98003196e-01 1.73489444e-05 3.22748915e-10]
 [7.09371985e-04 9.51785344e-01 1.93523902e-04]
 [7.20507985e-04 9.50981415e-01 1.84357052e-04]
 [3.95816670e-04 9.71151999e-01 1.23794125e-03]
 [5.13745015e-04 9.64600447e-01 5.35090628e-04]
 [4.29768882e-04 9.69350113e-01 9.4849264

In [4]:
Test(cost)
x.value = x_test
Forward(l7)
# Backprop(cost)
print(cost.value)
print(l7.value)

0.15565651951320741
[[9.97488177e-01 2.00364378e-05 7.71263933e-10]
 [9.97494451e-01 2.00034065e-05 7.70180145e-10]
 [9.97528899e-01 1.98216073e-05 7.64280348e-10]
 [9.97519407e-01 1.98717712e-05 7.65902462e-10]
 [9.97487099e-01 2.00421098e-05 7.71451898e-10]
 [9.97524316e-01 1.98458351e-05 7.65063199e-10]
 [9.97488198e-01 2.00363247e-05 7.71260372e-10]
 [9.97538116e-01 1.97728492e-05 7.62708062e-10]
 [9.97497775e-01 1.99858942e-05 7.69608590e-10]
 [9.97521707e-01 1.98596243e-05 7.65509600e-10]
 [9.97487610e-01 2.00394191e-05 7.71362938e-10]
 [9.89562491e-04 9.28752393e-01 1.02473678e-04]
 [1.17745830e-03 9.10037672e-01 6.04093183e-05]
 [2.94208352e-04 9.76398414e-01 4.92504261e-03]
 [4.75857064e-04 9.66790548e-01 1.02374651e-03]
 [3.09021920e-04 9.75671777e-01 4.18559805e-03]
 [5.95523929e-04 9.59502649e-01 4.99642202e-04]
 [2.48787495e-04 9.78563337e-01 8.62252461e-03]
 [2.67217657e-04 9.77697130e-01 6.78511126e-03]
 [2.64244872e-04 9.77838060e-01 7.04376886e-03]
 [2.44232402e-04 9.7

In [7]:
l7.last_left.last_left.last_left.sigma

array([[17.86679626, 15.20571773, 11.73965361]])

In [9]:
l6.last_left.last_left.last_left.mu

array([[ 62.75193885, -10.24435936, -44.20130475,  43.09050945]])