In [1]:
# -*- coding: utf-8 -*-
# @Time    : 2021/4/10 18:08
# @Author  : Weiming Mai
# @FileName: main.py
# @Software: PyCharm

import numpy as np
from Nodes import *
from Utils import *
from numpy import *
import xlrd
from sklearn import preprocessing

In [2]:
# read data
def excel_to_matrix(path, num):
    table = xlrd.open_workbook(path).sheets()[num]  # 获取第一个sheet表
    row = table.nrows  # 行数
    col = table.ncols  # 列数
    datamatrix = np.zeros((row, col))  # 生成一个nrows行ncols列，且元素均为0的初始矩阵
    for x in range(col):
        cols = np.matrix(table.col_values(x))  # 把list转换为矩阵进行矩阵操作
        datamatrix[:, x] = cols  # 按列把数据存进矩阵中
        # 数据归一化
#         min_max_scaler = preprocessing.MinMaxScaler()
#         datamatrix = min_max_scaler.fit_transform(datamatrix)
    return datamatrix

def mini_batch(batch_size, data_X, data_Y):
    idx = np.arange(0, data_X.shape[0])
    np.random.shuffle(idx)
    idx = idx[0:batch_size]

    return data_X[idx,:], data_Y[idx,:]

datafile = "C:/Users/13271/Desktop/git/DL/iris_test+train.xlsx"

data_x = excel_to_matrix(datafile, 0)
data_y = excel_to_matrix(datafile, 3)

x_test = excel_to_matrix(datafile, 1)
y_test = excel_to_matrix(datafile, 2)

In [14]:
batch_size = 32
x_batch, y_batch = mini_batch(batch_size, data_x, data_y)

x = Input(x_batch)
l2 = Dense(x, 10)
l2 = Sigmoid(l2)
l3 = Dense(l2, 8)
l3 = Sigmoid(l3)
l4 = Dense(l3, 8)
l4 = Sigmoid(l4)
l5 = Dense(l4, 6)
l5 = Sigmoid(l5)
l6 = Dense(l5,4)
l6 = Sigmoid(l6)
l7 = Dense(l6,3)
l7 = Sigmoid(l7)


y = Const(y_batch)
cost = MSE(l7, y)

Forward(cost)
p = Train(cost, [])
GD = G_D_Optimizer(p, 0.001) # lr
print(cost.value)
epoch = 1000
for ep in range(epoch):
    x_batch, y_batch = mini_batch(batch_size, data_x,data_y)
    x.value = x_batch
    y.value = y_batch
    for j in range(30):
        Forward(cost)
        Backprop(cost)
        GD.train()
    if ep % 100 == 0:
        print(cost.value)
#
#test = preprocessing.MinMaxScaler().fit_transform(np.array([[5.1,3.4,1.5,0.2]]))
# x.value = np.array([[5.1,3.4,1.5,0.2]])
# x.value = test
Test(cost)
x.value = x_test
Forward(cost)
# Backprop(cost)
print(cost.value)
print(l7.value)

0.7676436313279715
0.7304482919089375
0.66726565013703
0.6664390917745138
0.6475798428899432
0.6624102149943469
0.6569421315666527
0.6704865235400893
0.6656473491813822
0.6575973143552931
0.6676730695443706
0.6445329354396834
[[0.35553797 0.34580205 0.30025112]
 [0.35553796 0.34580203 0.30025111]
 [0.35553792 0.34580195 0.30025107]
 [0.35553793 0.34580197 0.30025109]
 [0.35553795 0.34580201 0.3002511 ]
 [0.35553797 0.34580205 0.30025112]
 [0.35553794 0.345802   0.30025109]
 [0.35553797 0.34580206 0.30025113]
 [0.35553794 0.34580199 0.30025109]
 [0.35553798 0.34580207 0.30025113]
 [0.35553796 0.34580203 0.30025111]
 [0.35553796 0.345802   0.30025106]
 [0.35553796 0.34580202 0.30025107]
 [0.35553799 0.34580207 0.30025109]
 [0.35553797 0.34580204 0.30025108]
 [0.35553793 0.34580196 0.30025105]
 [0.35553796 0.34580202 0.30025107]
 [0.35553797 0.34580205 0.30025108]
 [0.35553797 0.34580204 0.30025108]
 [0.355538   0.34580209 0.3002511 ]
 [0.35553794 0.34580197 0.30025106]
 [0.35553797 0.345

In [18]:
batch_size = 32
x_batch, y_batch = mini_batch(batch_size, data_x, data_y)

x = Input(x_batch)
l2 = Dense(x, 10)
l2 = batch_normalize(l2)
l2 = Sigmoid(l2)
l3 = Dense(l2, 8)
l3 = batch_normalize(l3)
l3 = Sigmoid(l3)
l4 = Dense(l3, 8)
l4 = batch_normalize(l4)
l4 = Sigmoid(l4)
l5 = Dense(l4, 6)
l5 = batch_normalize(l5)
l5 = Sigmoid(l5)
l6 = Dense(l5,4)
l6 = batch_normalize(l6)
l6 = Sigmoid(l6)
l7 = Dense(l6,3)
l7 = batch_normalize(l7)
l7 = Sigmoid(l7)


y = Const(y_batch)
cost = MSE(l7, y)

Forward(cost)
p = Train(cost, [])
GD = G_D_Optimizer(p, 0.1) # lr
print(cost.value)
epoch = 1000
for ep in range(epoch):
    x_batch, y_batch = mini_batch(batch_size, data_x,data_y)
    x.value = x_batch
    y.value = y_batch
    for j in range(5):
        Forward(cost)
        Backprop(cost)
        GD.train()
    if ep % 100 == 0:
        print(cost.value)
#
#test = preprocessing.MinMaxScaler().fit_transform(np.array([[5.1,3.4,1.5,0.2]]))
# x.value = np.array([[5.1,3.4,1.5,0.2]])
# x.value = test
# Test(cost)
x.value = x_test
Forward(cost)
# Backprop(cost)
print(cost.value)
print(l7.value)

0.7467672987924384
0.4008309424274237
0.05548756410937589
0.07769569885034543
0.010151229946111097
0.0603391816358979
0.06698625157341348
0.13499443309819534
0.06203909997542211
0.18173729904742736
0.1883380455030536
1.2625164040650578
[[9.98478948e-01 1.68729202e-05 4.28431424e-08]
 [9.98478973e-01 1.68727054e-05 4.28425971e-08]
 [9.98477531e-01 1.68855100e-05 4.28750946e-08]
 [9.98478595e-01 1.68760609e-05 4.28511152e-08]
 [9.98478802e-01 1.68742205e-05 4.28464433e-08]
 [9.98478662e-01 1.68754655e-05 4.28496038e-08]
 [9.98478643e-01 1.68756310e-05 4.28500240e-08]
 [9.98478974e-01 1.68726963e-05 4.28425739e-08]
 [9.98478685e-01 1.68752606e-05 4.28490836e-08]
 [9.98478973e-01 1.68726982e-05 4.28425787e-08]
 [9.98478919e-01 1.68731808e-05 4.28438040e-08]
 [2.50115611e-03 9.33179072e-01 2.53872816e-02]
 [2.50116432e-03 9.33119499e-01 2.54103891e-02]
 [2.50114619e-03 9.33310295e-01 2.53361818e-02]
 [2.50114401e-03 9.33432682e-01 2.52883576e-02]
 [2.50118032e-03 9.33029536e-01 2.54451976e-

In [17]:
Test(cost)
x.value = x_test
Forward(cost)
# Backprop(cost)
print(cost.value)
print(l7.value)

1.1456918330518189
[[9.97975936e-01 5.95917569e-02 2.75151036e-28]
 [9.97978142e-01 5.95790243e-02 2.74154998e-28]
 [9.97983669e-01 5.95474587e-02 2.72024776e-28]
 [9.97982713e-01 5.95528653e-02 2.72340945e-28]
 [9.97962961e-01 5.96672119e-02 2.81832183e-28]
 [9.97954523e-01 5.97164658e-02 2.86626528e-28]
 [9.97978589e-01 5.95764510e-02 2.73960953e-28]
 [9.97973164e-01 5.96078133e-02 2.76477218e-28]
 [9.97980472e-01 5.95656417e-02 2.73178714e-28]
 [9.97970445e-01 5.96236118e-02 2.77841776e-28]
 [9.97977258e-01 5.95841209e-02 2.74546865e-28]
 [1.83249624e-03 4.83921494e-01 2.71908959e-02]
 [1.83697154e-03 4.83816067e-01 2.60920902e-02]
 [1.83735330e-03 4.83808013e-01 2.60020443e-02]
 [1.83959965e-03 4.83766536e-01 2.56885528e-02]
 [1.83858127e-03 4.83785730e-01 2.57519110e-02]
 [1.83830940e-03 4.83790077e-01 2.57954382e-02]
 [1.85539692e-03 4.83326941e-01 2.49320779e-02]
 [1.84143067e-03 4.83720392e-01 2.56311812e-02]
 [1.84160678e-03 4.83715687e-01 2.56246809e-02]
 [1.83820600e-03 4.83

In [24]:
l5.last_left.last_left.last_right.value

array([[-10.5041726 ,  -5.24396421,  -4.530682  ]])